_BASE_: "../../../base-prompt_fourier_moco.yaml"
RUN_N_TIMES: 1
DATA:
  NAME: vtab-diabetic_retinopathy(config="btgraham-300")
  DATAPATH: "/shared/rc/spl/VTAB-1k/Specialized/"  #TODO: need to specify here
  NUMBER_CLASSES: 5
  MULTILABEL: False
MODEL:
  TYPE: "ssl-vit"
SOLVER:
  BASE_LR: 0.01
  WEIGHT_DECAY: 0.001
