_BASE_: "../base-prompt.yaml"
RUN_N_TIMES: 1
DATA:
  NAME: "StanfordCars"
  DATAPATH: "/shared/rc/spl/fgvc/Stanford-cars"  #TODO: need to specify here
  NUMBER_CLASSES: 196
  MULTILABEL: False
MODEL:
  TYPE: "vit"
SOLVER:
  BASE_LR: 5.0
  WEIGHT_DECAY: 0.0001
