_BASE_: "../../../base-prompt_fourier_mae.yaml"
RUN_N_TIMES: 1
DATA:
  NAME: "vtab-eurosat"
  DATAPATH: "/shared/rc/spl/VTAB-1k/Specialized/"  #TODO: need to specify here
  NUMBER_CLASSES: 10
  MULTILABEL: False
MODEL:
  TYPE: "ssl-vit"
SOLVER:
  BASE_LR: 0.01
  WEIGHT_DECAY: 0.001
