NUM_GPUS: 1
NUM_SHARDS: 1
OUTPUT_DIR: "output_fpt"
RUN_N_TIMES: 1
MODEL:
  TRANSFER_TYPE: "fpt"
  TYPE: "ssl-vit"
  LINEAR:
    MLP_SIZES: []
SOLVER:
  SCHEDULER: "cosine"
  PATIENCE: 300
  LOSS: "softmax"
  OPTIMIZER: "sgd"
  MOMENTUM: 0.9
  WEIGHT_DECAY: 0.0001
  LOG_EVERY_N: 100
  WARMUP_EPOCH: 10
  TOTAL_EPOCH: 100
DATA:
  NAME: "test"
  NUMBER_CLASSES: -1
  DATAPATH: ""
  FEATURE: "mocov3_vitb"
  BATCH_SIZE: 64