_BASE_: "../../../base-prompt_fourier_moco.yaml"
RUN_N_TIMES: 1
DATA:
  NAME: vtab-dsprites(predicted_attribute="label_orientation",num_classes=16)
  DATAPATH: "/shared/rc/spl/VTAB-1k/Structured/"  #TODO: need to specify here
  NUMBER_CLASSES: 16
  MULTILABEL: False
MODEL:
  TYPE: "ssl-vit"
SOLVER:
  BASE_LR: 0.01
  WEIGHT_DECAY: 0.001
